/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppEstimatesRouteImport } from './routes/_app.estimates'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppStorageRouteImport } from './routes/_app.storage'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppProductsIdIndexRouteImport } from './routes/_app.products.$id.index'
import { Route as AppProductsIdEditRouteImport } from './routes/_app.products.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppEstimatesRoute = AppEstimatesRouteImport.update({
  id: '/estimates',
  path: '/estimates',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStorageRoute = AppStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdIndexRoute = AppProductsIdIndexRouteImport.update({
  id: '/products/$id/',
  path: '/products/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdEditRoute = AppProductsIdEditRouteImport.update({
  id: '/products/$id/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estimates': typeof AppEstimatesRoute
  '/settings': typeof AppSettingsRoute
  '/storage': typeof AppStorageRoute
  '/team': typeof AppTeamRoute
  '/products/new': typeof AppProductsNewRoute
  '/products/': typeof AppProductsIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
  '/products/$id/': typeof AppProductsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof AppCategoriesRoute
  '/dashboard': typeof AppDashboardRoute
  '/estimates': typeof AppEstimatesRoute
  '/settings': typeof AppSettingsRoute
  '/storage': typeof AppStorageRoute
  '/team': typeof AppTeamRoute
  '/products/new': typeof AppProductsNewRoute
  '/products': typeof AppProductsIndexRoute
  '/products/$id/edit': typeof AppProductsIdEditRoute
  '/products/$id': typeof AppProductsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/estimates': typeof AppEstimatesRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/storage': typeof AppStorageRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/products/$id/edit': typeof AppProductsIdEditRoute
  '/_app/products/$id/': typeof AppProductsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/estimates'
    | '/settings'
    | '/storage'
    | '/team'
    | '/products/new'
    | '/products/'
    | '/products/$id/edit'
    | '/products/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/dashboard'
    | '/estimates'
    | '/settings'
    | '/storage'
    | '/team'
    | '/products/new'
    | '/products'
    | '/products/$id/edit'
    | '/products/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/estimates'
    | '/_app/settings'
    | '/_app/storage'
    | '/_app/team'
    | '/_app/products/new'
    | '/_app/products/'
    | '/_app/products/$id/edit'
    | '/_app/products/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/estimates': {
      id: '/_app/estimates'
      path: '/estimates'
      fullPath: '/estimates'
      preLoaderRoute: typeof AppEstimatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/storage': {
      id: '/_app/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof AppStorageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id/': {
      id: '/_app/products/$id/'
      path: '/products/$id'
      fullPath: '/products/$id/'
      preLoaderRoute: typeof AppProductsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id/edit': {
      id: '/_app/products/$id/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AppProductsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEstimatesRoute: typeof AppEstimatesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStorageRoute: typeof AppStorageRoute
  AppTeamRoute: typeof AppTeamRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsIdEditRoute: typeof AppProductsIdEditRoute
  AppProductsIdIndexRoute: typeof AppProductsIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEstimatesRoute: AppEstimatesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStorageRoute: AppStorageRoute,
  AppTeamRoute: AppTeamRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsIdEditRoute: AppProductsIdEditRoute,
  AppProductsIdIndexRoute: AppProductsIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
